version: "3.8"

services:
  db:
    image: postgres:12.2
    container_name: "comments-db"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hello
    networks:
      - fullstack
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  api:
    build: .
    container_name: "comments-rest-api"
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "hello"
      DB_DB: "postgres"
      DB_HOST: "db"
      DB_TABLE: "postgres"
      DB_PORT: 5432
      SSL_MODE: "disable"
    ports:
      - 8080:8080
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fullstack
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "hello"
      DB_DB: "postgres"
      DB_HOST: "db"
      DB_TABLE: "postgres"
      DB_PORT: 5432
      SSL_MODE: "disable"
    command: go test -tags=integration ./... -v
    ports:
      - 8080:8080
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      db:
        condition: service_healthy
    networks:
      - fullstack

volumes:
  db_data:

networks:
  fullstack:
    driver: bridge
